import { Actor, ActorDefinition, MockAccount, PlatformModuleDefinition, RoleFormField, UseCaseDefinition } from '../types';

export const ACTORS: ActorDefinition[] = [
  {
    id: 'super_administrator',
    label: 'Super Administrator',
    shortLabel: 'Super Admin',
    dashboardTitle: 'Super Administrator Control Center',
    dashboardSummary: 'Govern access, settings, system health, and portfolio-wide analytics.',
    accentColor: '#ef4444',
    accessLabel: 'Platform Governance',
    loginTitle: 'Secure platform command access',
    loginSummary: 'Review system-wide controls, account governance, and event-level visibility from one privileged entry point.',
    registrationSummary: 'Provision a high-trust account for platform governance, controls, and analytical oversight.',
    highlights: ['User governance', 'System settings', 'Event visibility'],
  },
  {
    id: 'finance_officer',
    label: 'Finance Officer',
    shortLabel: 'Finance',
    dashboardTitle: 'Finance Operations Workspace',
    dashboardSummary: 'Manage donors, receipts, allocations, reconciliation, and financial reporting.',
    accentColor: '#0f766e',
    accessLabel: 'Finance Operations',
    loginTitle: 'Enter the finance execution desk',
    loginSummary: 'Move from donor registration to reconciliation with a role workspace built around controlled money movement.',
    registrationSummary: 'Open a finance operations account with internal authorization and reporting identifiers.',
    highlights: ['Donor intake', 'Fund receipts', 'Bank reconciliation'],
  },
  {
    id: 'field_staff',
    label: 'Field Staff',
    shortLabel: 'Field Staff',
    dashboardTitle: 'Field Staff Service Desk',
    dashboardSummary: 'Submit claims and maintain field profile details with operational clarity.',
    accentColor: '#2563eb',
    accessLabel: 'Field Operations',
    loginTitle: 'Reach the field operations desk',
    loginSummary: 'Submit claims quickly, maintain field identity details, and stay aligned with the delivery environment.',
    registrationSummary: 'Create a field-facing account with region, deployment, and supervisor information.',
    highlights: ['Expense claims', 'Field identity', 'Deployment support'],
  },
  {
    id: 'project_manager',
    label: 'Project Manager',
    shortLabel: 'Project Manager',
    dashboardTitle: 'Project Budget Oversight',
    dashboardSummary: 'Review requests, monitor burn rate, and manage project budget health.',
    accentColor: '#7c3aed',
    accessLabel: 'Project Oversight',
    loginTitle: 'Open the project budget review cockpit',
    loginSummary: 'Track project burn, review requests, and keep implementation budgets inside approved controls.',
    registrationSummary: 'Create a project manager account with portfolio and cost-center ownership details.',
    highlights: ['Budget requests', 'Project monitoring', 'Approval routing'],
  },
  {
    id: 'executive_director',
    label: 'Executive Director',
    shortLabel: 'Executive Director',
    dashboardTitle: 'Executive Director Briefing',
    dashboardSummary: 'Approve requisitions and review strategic and analytical views of the platform.',
    accentColor: '#d97706',
    accessLabel: 'Executive Approval',
    loginTitle: 'Enter the executive approval suite',
    loginSummary: 'Handle final requisitions and read strategic performance from a concise leadership interface.',
    registrationSummary: 'Provision an executive account with mandate, approval ceiling, and board-facing context.',
    highlights: ['Final requisitions', 'Strategic dashboard', 'Portfolio analytics'],
  },
  {
    id: 'external_auditor',
    label: 'External Auditor',
    shortLabel: 'Auditor',
    dashboardTitle: 'External Auditor Review Board',
    dashboardSummary: 'Inspect audit evidence, verify compliance, and review account profile details.',
    accentColor: '#334155',
    accessLabel: 'Assurance Review',
    loginTitle: 'Access the audit assurance workspace',
    loginSummary: 'Inspect immutable traces, verify controls, and work through compliance evidence with a clear review surface.',
    registrationSummary: 'Create an auditor account with firm, certification, and engagement references.',
    highlights: ['Audit trail review', 'Compliance verification', 'Independent assurance'],
  },
  {
    id: 'donor_user',
    label: 'Donor User',
    shortLabel: 'Donor',
    dashboardTitle: 'Donor Relationship Portal',
    dashboardSummary: 'Access donor-facing information, transaction summaries, and profile settings.',
    accentColor: '#16a34a',
    accessLabel: 'Donor Experience',
    loginTitle: 'Enter the donor relationship portal',
    loginSummary: 'See donations, project impact, and transaction history in a donor-facing experience rather than an internal dashboard.',
    registrationSummary: 'Open a donor profile with giving preferences, donor type, and compliance-relevant identity details.',
    highlights: ['Donor portal', 'Transaction summaries', 'Profile maintenance'],
  },
];

export const ACTOR_FORM_FIELDS: Record<Actor, RoleFormField[]> = {
  super_administrator: [
    { key: 'organization_unit', label: 'Organization Unit', type: 'text', placeholder: 'Central Administration' },
    { key: 'staff_id', label: 'Staff ID', type: 'text', placeholder: 'ADM-204' },
    {
      key: 'security_clearance',
      label: 'Security Clearance',
      type: 'select',
      placeholder: 'Select clearance',
      options: [
        { label: 'Tier 1', value: 'Tier 1' },
        { label: 'Tier 2', value: 'Tier 2' },
        { label: 'Tier 3', value: 'Tier 3' },
      ],
    },
  ],
  finance_officer: [
    { key: 'finance_unit', label: 'Finance Unit', type: 'text', placeholder: 'Treasury and Controls' },
    { key: 'authorization_limit', label: 'Authorization Limit', type: 'text', placeholder: 'USD 25,000' },
    { key: 'payroll_code', label: 'Payroll Code', type: 'text', placeholder: 'FIN-7781' },
  ],
  field_staff: [
    { key: 'operational_region', label: 'Operational Region', type: 'text', placeholder: 'Eastern Province' },
    { key: 'base_station', label: 'Base Station', type: 'text', placeholder: 'Kayonza Field Office' },
    { key: 'supervisor_name', label: 'Supervisor Name', type: 'text', placeholder: 'Regional Coordinator' },
  ],
  project_manager: [
    { key: 'project_portfolio', label: 'Project Portfolio', type: 'text', placeholder: 'Health Systems Strengthening' },
    { key: 'cost_center', label: 'Cost Center', type: 'text', placeholder: 'CC-3304' },
    {
      key: 'approval_tier',
      label: 'Approval Tier',
      type: 'select',
      placeholder: 'Select tier',
      options: [
        { label: 'Tier A', value: 'Tier A' },
        { label: 'Tier B', value: 'Tier B' },
        { label: 'Tier C', value: 'Tier C' },
      ],
    },
  ],
  executive_director: [
    { key: 'office_title', label: 'Office Title', type: 'text', placeholder: 'Executive Director' },
    { key: 'approval_ceiling', label: 'Approval Ceiling', type: 'text', placeholder: 'USD 100,000' },
    { key: 'board_liaison', label: 'Board Liaison', type: 'text', placeholder: 'Governance Committee' },
  ],
  external_auditor: [
    { key: 'audit_firm', label: 'Audit Firm', type: 'text', placeholder: 'Independent Assurance LLP' },
    { key: 'engagement_code', label: 'Engagement Code', type: 'text', placeholder: 'AUD-2026-Q2' },
    { key: 'certification_id', label: 'Certification ID', type: 'text', placeholder: 'CPA-44721' },
  ],
  donor_user: [
    {
      key: 'donor_type',
      label: 'Donor Type',
      type: 'select',
      placeholder: 'Select donor type',
      options: [
        { label: 'Individual', value: 'Individual' },
        { label: 'Corporate', value: 'Corporate' },
        { label: 'Foundation', value: 'Foundation' },
      ],
    },
    { key: 'preferred_cause', label: 'Preferred Cause', type: 'text', placeholder: 'Maternal and Child Health' },
    { key: 'tax_residence', label: 'Tax Residence', type: 'text', placeholder: 'Rwanda' },
  ],
};

export const ACTOR_LOGIN_IDS: Record<Actor, { label: string; placeholder: string }> = {
  super_administrator: { label: 'Administrator Email', placeholder: 'superadmin@ngofund.org' },
  finance_officer: { label: 'Finance Email', placeholder: 'finance@ngofund.org' },
  field_staff: { label: 'Field Email', placeholder: 'field@ngofund.org' },
  project_manager: { label: 'Project Manager Email', placeholder: 'manager@ngofund.org' },
  executive_director: { label: 'Executive Email', placeholder: 'director@ngofund.org' },
  external_auditor: { label: 'Auditor Email', placeholder: 'auditor@ngofund.org' },
  donor_user: { label: 'Donor Email', placeholder: 'donor@ngofund.org' },
};

export const PLATFORM_MODULES: PlatformModuleDefinition[] = [
  {
    id: 'donor-management',
    title: 'Donor Management',
    summary: 'Centralizes donor registration, contribution visibility, engagement, status, and donor lookup.',
    uiElements: [
      'Donor registration form',
      'Contribution history table',
      'Donor dashboard cards',
      'Communication log',
      'Donor status indicators',
      'Bulk import/export controls',
      'Search and filter panel',
    ],
    features: [
      'Stores donor details',
      'Tracks contribution history',
      'Supports donor categorization',
      'Prepares acknowledgments',
      'Tracks engagement activity',
    ],
    useCaseIds: ['register-new-donor', 'access-donor-portal', 'view-transaction-summaries'],
  },
  {
    id: 'fund-collection-tracking',
    title: 'Fund Collection & Tracking',
    summary: 'Records incoming funds, tracks transaction status, supports reconciliation, and visualizes fund movement.',
    uiElements: [
      'Fund receipt entry form',
      'Incoming funds dashboard',
      'Transaction status indicators',
      'Bank reconciliation interface',
      'Currency support panel',
      'Fund flow chart',
      'Receipt upload area',
    ],
    features: [
      'Records received funds',
      'Monitors financial transactions',
      'Supports real-time tracking',
      'Matches transactions',
      'Handles multiple currencies',
    ],
    useCaseIds: ['record-fund-receipt', 'bank-reconciliation', 'view-transaction-summaries'],
  },
  {
    id: 'project-fund-allocation',
    title: 'Project Fund Allocation',
    summary: 'Assigns funding to projects, monitors budget utilization, and supports allocation approvals.',
    uiElements: [
      'Project budget list',
      'Fund allocation form',
      'Disbursement tracker',
      'Budget utilization gauge',
      'Reallocation workflow',
      'Project funding history',
    ],
    features: [
      'Allocates funds to projects',
      'Tracks disbursement progress',
      'Monitors budget adherence',
      'Supports reallocation approvals',
      'Shows utilization dashboards',
    ],
    useCaseIds: ['allocate-funds-to-projects', 'review-budget-requests', 'monitor-project-budget'],
  },
  {
    id: 'expenditure-monitoring',
    title: 'Expenditure Monitoring',
    summary: 'Captures expenses, routes approvals, compares spend to budget, and preserves receipt evidence.',
    uiElements: [
      'Expense entry form',
      'Approval workflow board',
      'Budget comparison chart',
      'Receipt attachment area',
      'Audit visibility panel',
      'Expense category filters',
    ],
    features: [
      'Monitors expenses',
      'Supports approval workflows',
      'Tracks receipts',
      'Maintains audit compliance',
      'Compares budget and actuals',
    ],
    useCaseIds: ['submit-expense-claims', 'review-budget-requests', 'final-approve-requisitions'],
  },
  {
    id: 'reporting-analytics',
    title: 'Reporting & Analytics',
    summary: 'Generates finance, donor, project, and audit reporting with charts and export-oriented outputs.',
    uiElements: [
      'Report type selector',
      'KPI dashboard cards',
      'Interactive charts',
      'Custom report builder',
      'Export controls',
      'Schedule panel',
      'Audit log viewer',
    ],
    features: [
      'Generates financial summaries',
      'Supports donor reports',
      'Builds dashboards',
      'Prepares audit logs',
      'Supports scheduled reporting',
    ],
    useCaseIds: ['generate-financial-reports', 'view-analytical-dashboard', 'view-strategic-dashboard'],
  },
  {
    id: 'staff-operations',
    title: 'Staff & Operations',
    summary: 'Captures staff requirements, process documentation, feedback, validation, and operational sign-off.',
    uiElements: [
      'Interview capture form',
      'Process documentation editor',
      'Staff feedback area',
      'Requirement validation tracker',
      'Process flow visualization',
      'Approval sign-off interface',
    ],
    features: [
      'Captures interviews',
      'Documents processes',
      'Collects staff input',
      'Tracks requirement completion',
      'Supports collaborative validation',
    ],
    useCaseIds: ['capture-staff-requirements', 'update-user-profile'],
  },
  {
    id: 'testing-validation',
    title: 'System Testing & Validation',
    summary: 'Tracks test cases, bugs, UAT feedback, validation status, environments, and release notes.',
    uiElements: [
      'Test case table',
      'Bug tracking board',
      'UAT feedback form',
      'Validation dashboard',
      'Environment selector',
      'Release history panel',
    ],
    features: [
      'Tracks test progress',
      'Captures validation results',
      'Manages UAT feedback',
      'Supports bug resolution',
      'Documents release readiness',
    ],
    useCaseIds: ['manage-testing-validation'],
  },
  {
    id: 'user-access-management',
    title: 'User & Access Management',
    summary: 'Manages accounts, role assignments, permissions, login activity, profiles, and secure settings.',
    uiElements: [
      'User management table',
      'Role assignment interface',
      'Permission matrix',
      'Login activity log',
      'Profile management',
      'Session timeout settings',
    ],
    features: [
      'Controls role-based access',
      'Supports granular permissions',
      'Monitors activity',
      'Improves security compliance',
      'Maintains profiles',
    ],
    useCaseIds: ['manage-user-accounts', 'manage-system-settings', 'view-event-logs', 'update-user-profile'],
  },
  {
    id: 'dashboard-transparency',
    title: 'Dashboard & Transparency Portal',
    summary: 'Provides centralized visibility into funding operations, impact, alerts, scorecards, and role dashboards.',
    uiElements: [
      'Financial overview widgets',
      'Fund tracking visualization',
      'Transparency scorecard',
      'Donor impact summary',
      'Project funding heat map',
      'Recent activity feed',
      'Custom dashboard layout',
    ],
    features: [
      'Centralizes visibility',
      'Shows transparency metrics',
      'Provides real-time alerts',
      'Supports role-based views',
      'Summarizes donor impact',
    ],
    useCaseIds: ['view-analytical-dashboard', 'view-strategic-dashboard', 'access-donor-portal'],
  },
  {
    id: 'audit-compliance',
    title: 'Audit & Compliance',
    summary: 'Supports audit trail exploration, compliance checklists, discrepancy review, export, and traceability.',
    uiElements: [
      'Audit trail explorer',
      'Compliance checklist',
      'Audit document repository',
      'Discrepancy report panel',
      'Audit export utility',
      'Compliance status indicators',
    ],
    features: [
      'Structures audit-friendly data',
      'Automates compliance reporting',
      'Maintains transaction traceability',
      'Retains secure documents',
      'Supports external assurance',
    ],
    useCaseIds: ['maintain-audit-trail', 'view-audit-trail', 'verify-compliance-checklist'],
  },
];

export const USE_CASES: UseCaseDefinition[] = [
  {
    id: 'manage-user-accounts',
    moduleId: 'user-access-management',
    title: 'Manage User Accounts',
    summary: 'Create, review, and govern system accounts and role assignments.',
    actors: ['super_administrator'],
  },
  {
    id: 'manage-system-settings',
    moduleId: 'user-access-management',
    title: 'Manage System Settings',
    summary: 'Adjust platform-wide operational, notification, and control settings.',
    actors: ['super_administrator'],
  },
  {
    id: 'view-event-logs',
    moduleId: 'user-access-management',
    title: 'View Event Logs',
    summary: 'Inspect significant platform events, alerts, and actor activity.',
    actors: ['super_administrator'],
  },
  {
    id: 'view-analytical-dashboard',
    moduleId: 'reporting-analytics',
    title: 'View Analytical Dashboard',
    summary: 'Review analytics across fundraising, projects, and approvals.',
    actors: ['super_administrator', 'executive_director'],
  },
  {
    id: 'register-new-donor',
    moduleId: 'donor-management',
    title: 'Register New Donor',
    summary: 'Capture donor details and add them to the finance operating roster.',
    actors: ['finance_officer'],
  },
  {
    id: 'record-fund-receipt',
    moduleId: 'fund-collection-tracking',
    title: 'Record Fund Receipt',
    summary: 'Post incoming donations and mark receipts against projects.',
    actors: ['finance_officer'],
  },
  {
    id: 'allocate-funds-to-projects',
    moduleId: 'project-fund-allocation',
    title: 'Allocate Funds to Projects',
    summary: 'Distribute available funding into approved project buckets.',
    actors: ['finance_officer'],
  },
  {
    id: 'bank-reconciliation',
    moduleId: 'fund-collection-tracking',
    title: 'Bank Reconciliation',
    summary: 'Reconcile ledger values with bank statement references.',
    actors: ['finance_officer'],
  },
  {
    id: 'generate-financial-reports',
    moduleId: 'reporting-analytics',
    title: 'Generate Financial Reports',
    summary: 'Prepare period-based financial output for leadership and compliance.',
    actors: ['finance_officer'],
  },
  {
    id: 'maintain-audit-trail',
    moduleId: 'audit-compliance',
    title: 'Maintain Audit Trail',
    summary: 'Record financial events to preserve traceability and review readiness.',
    actors: ['finance_officer'],
  },
  {
    id: 'submit-expense-claims',
    moduleId: 'expenditure-monitoring',
    title: 'Submit Expense Claims',
    summary: 'Submit new reimbursement and field expense requests.',
    actors: ['field_staff'],
  },
  {
    id: 'capture-staff-requirements',
    moduleId: 'staff-operations',
    title: 'Capture Staff Requirements',
    summary: 'Collect interviews, process notes, feedback, validation status, and sign-off evidence.',
    actors: ['super_administrator', 'field_staff', 'project_manager', 'executive_director'],
  },
  {
    id: 'manage-testing-validation',
    moduleId: 'testing-validation',
    title: 'Manage Testing & Validation',
    summary: 'Track test cases, bugs, UAT feedback, validation status, environments, and release readiness.',
    actors: ['super_administrator', 'external_auditor', 'executive_director'],
  },
  {
    id: 'update-user-profile',
    moduleId: 'staff-operations',
    title: 'Update User Profile',
    summary: 'Maintain account information, contact details, and profile preferences.',
    actors: ['field_staff', 'project_manager', 'external_auditor', 'donor_user'],
  },
  {
    id: 'review-budget-requests',
    moduleId: 'project-fund-allocation',
    title: 'Review Budget Requests',
    summary: 'Assess project budget requests and send them forward or reject them.',
    actors: ['project_manager'],
  },
  {
    id: 'monitor-project-budget',
    moduleId: 'project-fund-allocation',
    title: 'Monitor Project Budget',
    summary: 'Track spend, variance, and remaining balance across projects.',
    actors: ['project_manager'],
  },
  {
    id: 'final-approve-requisitions',
    moduleId: 'expenditure-monitoring',
    title: 'Final Approve Requisitions',
    summary: 'Review high-level requisitions and issue final approval decisions.',
    actors: ['executive_director'],
  },
  {
    id: 'view-strategic-dashboard',
    moduleId: 'dashboard-transparency',
    title: 'View Strategic Dashboard',
    summary: 'Review strategic KPIs on funding, delivery, and approval throughput.',
    actors: ['executive_director'],
  },
  {
    id: 'view-audit-trail',
    moduleId: 'audit-compliance',
    title: 'View Audit Trail',
    summary: 'Inspect immutable operational evidence and transaction lineage.',
    actors: ['external_auditor'],
  },
  {
    id: 'verify-compliance-checklist',
    moduleId: 'audit-compliance',
    title: 'Verify Compliance Checklist',
    summary: 'Verify required governance and operational compliance items.',
    actors: ['external_auditor'],
  },
  {
    id: 'access-donor-portal',
    moduleId: 'dashboard-transparency',
    title: 'Access Donor Portal',
    summary: 'Open the donor-facing portal for impact, giving, and engagement context.',
    actors: ['donor_user'],
  },
  {
    id: 'view-transaction-summaries',
    moduleId: 'donor-management',
    title: 'View Transaction Summaries',
    summary: 'Review personal donation history and transaction outcomes.',
    actors: ['donor_user'],
  },
];

export const MOCK_ACCOUNTS: MockAccount[] = [
  {
    id: 'acct-001',
    actor: 'super_administrator',
    email: 'superadmin@ngofund.org',
    password: 'demo123',
    name: 'Nadine Uwase',
    metadata: {
      organization_unit: 'Central Administration',
      staff_id: 'ADM-204',
      security_clearance: 'Tier 3',
    },
  },
  {
    id: 'acct-002',
    actor: 'finance_officer',
    email: 'finance@ngofund.org',
    password: 'demo123',
    name: 'Michael Finance',
    metadata: {
      finance_unit: 'Treasury and Controls',
      authorization_limit: 'USD 25,000',
      payroll_code: 'FIN-7781',
    },
  },
  {
    id: 'acct-003',
    actor: 'field_staff',
    email: 'field@ngofund.org',
    password: 'demo123',
    name: 'Grace Field',
    metadata: {
      operational_region: 'Eastern Province',
      base_station: 'Kayonza Field Office',
      supervisor_name: 'Regional Coordinator',
    },
  },
  {
    id: 'acct-004',
    actor: 'project_manager',
    email: 'manager@ngofund.org',
    password: 'demo123',
    name: 'Patrick Manager',
    metadata: {
      project_portfolio: 'Health Systems Strengthening',
      cost_center: 'CC-3304',
      approval_tier: 'Tier B',
    },
  },
  {
    id: 'acct-005',
    actor: 'executive_director',
    email: 'director@ngofund.org',
    password: 'demo123',
    name: 'Aline Director',
    metadata: {
      office_title: 'Executive Director',
      approval_ceiling: 'USD 100,000',
      board_liaison: 'Governance Committee',
    },
  },
  {
    id: 'acct-006',
    actor: 'external_auditor',
    email: 'auditor@ngofund.org',
    password: 'demo123',
    name: 'Lisa Auditor',
    metadata: {
      audit_firm: 'Independent Assurance LLP',
      engagement_code: 'AUD-2026-Q2',
      certification_id: 'CPA-44721',
    },
  },
  {
    id: 'acct-007',
    actor: 'donor_user',
    email: 'donor@ngofund.org',
    password: 'demo123',
    name: 'Sarah Donor',
    metadata: {
      donor_type: 'Individual',
      preferred_cause: 'Maternal and Child Health',
      tax_residence: 'Rwanda',
    },
  },
];
