import React from 'react';
import { StatCard } from '../../components/StatCard';
import { Button } from '../../components/Button';
import { Percent, ClipboardCheck, AlertTriangle, Archive, Plus, Filter, Download, CheckCheck, Upload, Eye, FileText, Shield, Bell, FileDown } from 'lucide-react';
import { RiskAssessmentChart } from '../../components/charts/RiskAssessmentChart';

const auditTrail = [
  { icon: '💰', title: 'Donation Received', description: 'Transaction ID: TXN-2024-00125 | Amount: $150 | Donor: Sarah Donor', timestamp: '2024-05-15 14:30:25 | User: System | IP: 41.202.207.5' },
  { icon: '🛡️', title: 'User Permission Changed', description: 'User: Robert Johnson | Role: Staff → Finance Officer', timestamp: '2024-05-15 14:15:10 | Modified by: John Admin | IP: 192.168.1.100' },
  { icon: '💳', title: 'Expense Approved', description: 'Expense ID: EXP-2024-00125 | Amount: $2,500 | Category: Medical Supplies', timestamp: '2024-05-15 13:45:30 | Approved by: John Admin | IP: 192.168.1.100' },
  { icon: '📊', title: 'Project Fund Allocated', description: 'Project: Hospital Equipment | Amount: $5,000 | Allocated by: Michael Finance', timestamp: '2024-05-15 13:30:15 | IP: 192.168.1.101' },
  { icon: '🔍', title: 'Audit Report Generated', description: 'Report: Q2 2024 Financial Compliance | Generated by: Lisa Auditor', timestamp: '2024-05-15 12:20:45 | IP: 192.168.1.102' },
];

const complianceItems = [
  { title: 'Financial Statement Accuracy', description: 'All financial statements reconciled and verified', completed: true },
  { title: 'Donor Data Privacy', description: 'GDPR and data protection compliance verified', completed: true },
  { title: 'Receipt Documentation', description: 'All expense receipts properly documented and stored', completed: false },
  { title: 'User Access Controls', description: 'Role-based access properly configured and monitored', completed: true },
  { title: 'Annual Tax Compliance', description: 'Tax filing and compliance documentation updated', completed: false },
];

const exceptions = [
  { id: 'EXC-001', type: 'Data Discrepancy', module: 'Fund Tracking', description: 'Bank reconciliation mismatch: $250 difference', severity: 'Medium', date: '2024-05-15', status: 'Investigating', assignedTo: 'Michael Finance' },
  { id: 'EXC-002', type: 'Compliance Gap', module: 'User Management', description: 'Inactive users not deactivated after 90 days', severity: 'Low', date: '2024-05-14', status: 'Resolved', assignedTo: 'John Admin' },
  { id: 'EXC-003', type: 'Security Alert', module: 'Security', description: 'Multiple failed login attempts from suspicious IP', severity: 'High', date: '2024-05-13', status: 'Resolved', assignedTo: 'System' },
];

const documents = [
  { name: 'Q1 2024 Financial Audit', type: 'pdf', date: 'May 10, 2024', size: '2.4 MB' },
  { name: 'Compliance Report 2023', type: 'word', date: 'May 5, 2024', size: '1.8 MB' },
  { name: 'Donor Data Export', type: 'excel', date: 'May 1, 2024', size: '850 KB' },
];

export const AuditCompliance: React.FC = () => {
  return (
    <div className="p-8">
      <div className="bg-white rounded-lg shadow-sm p-6 border border-[#dee2e6] mb-8">
        <h2 className="text-3xl font-bold text-[#212529] m-0">Audit & Compliance Module</h2>
        <p className="text-[#6c757d] text-sm mt-2">Maintain audit-friendly data structure, automate compliance reporting, ensure full transaction traceability, and manage audit documentation.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        <StatCard title="Compliance Rate" value="96%" icon={Percent} iconBgClass="bg-[rgba(255,152,0,0.1)] text-[#FF9800]" trend="Excellent" trendDirection="up" />
        <StatCard title="Audits Completed" value="24" icon={ClipboardCheck} iconBgClass="bg-[rgba(255,152,0,0.1)] text-[#FF9800]" trend="2 this month" trendDirection="up" />
        <StatCard title="Open Findings" value="3" icon={AlertTriangle} iconBgClass="bg-[rgba(255,152,0,0.1)] text-[#FF9800]" trend="Low risk" trendDirection="down" />
        <StatCard title="Document Retention" value="100%" icon={Archive} iconBgClass="bg-[rgba(255,152,0,0.1)] text-[#FF9800]" trend="Compliant" trendDirection="up" />
      </div>

      <div className="bg-white rounded-lg shadow-sm p-6 border border-[#dee2e6] mb-8 flex flex-wrap gap-4 items-center">
        <div className="flex items-center gap-2">
          <label className="font-semibold text-[#212529]">Filter by:</label>
          <select className="border border-[#dee2e6] rounded-lg px-3 py-2 text-sm">
            <option>All Audit Types</option>
            <option>Financial</option>
            <option>Operational</option>
            <option>Compliance</option>
            <option>Security</option>
          </select>
        </div>
        <select className="border border-[#dee2e6] rounded-lg px-3 py-2 text-sm">
          <option>All Status</option>
          <option>Completed</option>
          <option>In Progress</option>
          <option>Scheduled</option>
          <option>Overdue</option>
        </select>
        <div className="flex-1"></div>
        <Button icon={Plus}>Schedule Audit</Button>
      </div>

      <h3 className="text-2xl font-bold text-[#212529] mb-4 pb-3 border-b border-[#dee2e6]">Audit Trail Explorer</h3>
      <div className="bg-white rounded-lg shadow-sm border border-[#dee2e6] overflow-hidden mb-8">
        <div className="bg-[#f8f9fa] px-6 py-4 flex justify-between items-center border-b border-[#dee2e6]">
          <h3 className="text-xl font-bold text-[#212529] m-0">Complete Audit Trail</h3>
          <div className="flex gap-2">
            <Button variant="outline" icon={Filter}>Advanced Filter</Button>
            <Button variant="outline" icon={Download}>Export Trail</Button>
          </div>
        </div>
        <div className="p-6 max-h-96 overflow-y-auto">
          {auditTrail.map((item, index) => (
            <div key={index} className="flex gap-4 p-4 border-b border-[#dee2e6] last:border-b-0">
              <div className="w-10 h-10 bg-[rgba(255,152,0,0.1)] rounded-lg flex items-center justify-center text-lg">
                {item.icon}
              </div>
              <div className="flex-1">
                <div className="font-semibold text-[#212529]">{item.title}</div>
                <div className="text-[#6c757d] text-sm">{item.description}</div>
                <div className="text-[#6c757d] text-xs mt-1">{item.timestamp}</div>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
        <div className="bg-white rounded-lg shadow-sm border border-[#dee2e6] p-6">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-xl font-bold text-[#212529] m-0">Compliance Checklist</h3>
            <Button variant="outline" icon={CheckCheck}>Mark Complete</Button>
          </div>
          <div className="space-y-4">
            {complianceItems.map((item, index) => (
              <div key={index} className="flex gap-3 items-start">
                <input 
                  type="checkbox" 
                  defaultChecked={item.completed}
                  className="w-4 h-4 text-[#FF9800] rounded mt-1"
                />
                <div className="flex-1">
                  <div className="font-semibold text-[#212529]">{item.title}</div>
                  <div className="text-[#6c757d] text-sm">{item.description}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-sm border border-[#dee2e6] p-6">
          <h3 className="text-xl font-bold text-[#212529] mb-6 m-0">Risk Assessment Dashboard</h3>
          <RiskAssessmentChart />
        </div>
      </div>

      <h3 className="text-2xl font-bold text-[#212529] mb-4 pb-3 border-b border-[#dee2e6]">Document Repository</h3>
      <div className="bg-white rounded-lg shadow-sm border border-[#dee2e6] overflow-hidden mb-8">
        <div className="bg-[#f8f9fa] px-6 py-4 flex justify-between items-center border-b border-[#dee2e6]">
          <h3 className="text-xl font-bold text-[#212529] m-0">Audit Document Management</h3>
          <Button icon={Upload}>Upload Document</Button>
        </div>
        <div className="p-6">
          <div className="border-2 border-dashed border-[#dee2e6] rounded-lg p-8 text-center mb-6">
            <Upload className="w-12 h-12 text-[#6c757d] mx-auto mb-4" />
            <h4 className="text-[#212529] mb-2">Upload Audit Documents</h4>
            <p className="text-[#6c757d] mb-4">Drag and drop audit documents here or click to browse</p>
            <p className="text-[#6c757d] text-sm">Supported formats: PDF, Word, Excel, Images</p>
          </div>
          
          <h4 className="text-[#212529] mb-4">Recent Audit Documents</h4>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {documents.map((doc, index) => (
              <div key={index} className="bg-[#f8f9fa] p-4 rounded-lg">
                <div className="flex items-center gap-2 mb-2">
                  <FileText className="w-5 h-5 text-[#FF9800]" />
                  <div className="font-semibold text-[#212529]">{doc.name}</div>
                </div>
                <div className="text-sm text-[#6c757d]">Uploaded: {doc.date}</div>
                <div className="text-sm text-[#6c757d]">Size: {doc.size}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <h3 className="text-2xl font-bold text-[#212529] mb-4 pb-3 border-b border-[#dee2e6]">Exception & Discrepancy Reports</h3>
      <div className="bg-white rounded-lg shadow-sm border border-[#dee2e6] overflow-hidden mb-8">
        <div className="bg-[#f8f9fa] px-6 py-4 flex justify-between items-center border-b border-[#dee2e6]">
          <h3 className="text-xl font-bold text-[#212529] m-0">Exception Management</h3>
          <Button variant="outline" icon={Download}>Export Exceptions</Button>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-[#f8f9fa]">
              <tr>
                <th className="px-6 py-4 text-left text-sm font-semibold text-[#212529]">Exception ID</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-[#212529]">Type</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-[#212529]">Module</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-[#212529]">Description</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-[#212529]">Severity</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-[#212529]">Date Detected</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-[#212529]">Status</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-[#212529]">Assigned To</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-[#212529]">Actions</th>
              </tr>
            </thead>
            <tbody>
              {exceptions.map((exception, index) => (
                <tr key={index} className="border-b border-[#dee2e6] hover:bg-[#f8f9fa]">
                  <td className="px-6 py-4 text-sm text-[#495057]">{exception.id}</td>
                  <td className="px-6 py-4 text-sm text-[#495057]">{exception.type}</td>
                  <td className="px-6 py-4 text-sm text-[#495057]">{exception.module}</td>
                  <td className="px-6 py-4 text-sm text-[#495057]">{exception.description}</td>
                  <td className="px-6 py-4">
                    <span className={`inline-block px-3 py-1 rounded-full text-xs font-semibold ${
                      exception.severity === 'High' ? 'bg-[rgba(244,67,54,0.15)] text-[#F44336]' :
                      exception.severity === 'Medium' ? 'bg-[rgba(255,152,0,0.15)] text-[#FF9800]' :
                      'bg-[rgba(76,175,80,0.15)] text-[#4CAF50]'
                    }`}>
                      {exception.severity}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-sm text-[#495057]">{exception.date}</td>
                  <td className="px-6 py-4">
                    <span className={`inline-block px-3 py-1 rounded-full text-xs font-semibold ${
                      exception.status === 'Resolved' ? 'bg-[rgba(76,175,80,0.15)] text-[#4CAF50]' : 'bg-[rgba(255,152,0,0.15)] text-[#FF9800]'
                    }`}>
                      {exception.status}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-sm text-[#495057]">{exception.assignedTo}</td>
                  <td className="px-6 py-4">
                    <Button variant="outline" size="sm" icon={Eye}></Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white rounded-lg p-6 text-center border border-[#dee2e6] hover:border-[#FFC857] hover:shadow-md transition-all cursor-pointer">
          <div className="w-15 h-15 bg-[rgba(255,200,87,0.1)] rounded-lg flex items-center justify-center mx-auto mb-4">
            <FileDown className="w-7 h-7 text-[#FFC857]" />
          </div>
          <div className="font-semibold text-[#212529] mb-2">Generate Audit Report</div>
          <p className="text-sm text-[#6c757d]">Create comprehensive audit report</p>
        </div>
        <div className="bg-white rounded-lg p-6 text-center border border-[#dee2e6] hover:border-[#FFC857] hover:shadow-md transition-all cursor-pointer">
          <div className="w-15 h-15 bg-[rgba(255,200,87,0.1)] rounded-lg flex items-center justify-center mx-auto mb-4">
            <Shield className="w-7 h-7 text-[#FFC857]" />
          </div>
          <div className="font-semibold text-[#212529] mb-2">Compliance Dashboard</div>
          <p className="text-sm text-[#6c757d]">View compliance metrics</p>
        </div>
        <div className="bg-white rounded-lg p-6 text-center border border-[#dee2e6] hover:border-[#FFC857] hover:shadow-md transition-all cursor-pointer">
          <div className="w-15 h-15 bg-[rgba(255,200,87,0.1)] rounded-lg flex items-center justify-center mx-auto mb-4">
            <Bell className="w-7 h-7 text-[#FFC857]" />
          </div>
          <div className="font-semibold text-[#212529] mb-2">Alert Configuration</div>
          <p className="text-sm text-[#6c757d]">Set up audit alerts</p>
        </div>
        <div className="bg-white rounded-lg p-6 text-center border border-[#dee2e6] hover:border-[#FFC857] hover:shadow-md transition-all cursor-pointer">
          <div className="w-15 h-15 bg-[rgba(255,200,87,0.1)] rounded-lg flex items-center justify-center mx-auto mb-4">
            <Archive className="w-7 h-7 text-[#FFC857]" />
          </div>
          <div className="font-semibold text-[#212529] mb-2">Document Retention</div>
          <p className="text-sm text-[#6c757d]">Manage audit document storage</p>
        </div>
      </div>
    </div>
  );
};